name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
   
  build:
    runs-on: ubuntu-16.04

    env:
      DEVICE: le2
      VENDOR: leeco
      
    steps:
    - name: Checkout
      uses: actions/checkout@master
    
    - name: Initialization environment
      run: |
        sudo apt-get update
        sudo apt-get install -y \
        openjdk-8-jdk android-tools-adb bc \
        bison build-essential curl flex g++-multilib \
        gcc-multilib gnupg gperf imagemagick lib32ncurses5-dev \
        lib32readline-dev lib32z1-dev libesd0-dev liblz4-tool \
        libncurses5-dev libsdl1.2-dev libssl-dev libwxgtk3.0-dev \
        libxml2 libxml2-utils lzop pngcrush rsync schedtool \
        squashfs-tools xsltproc yasm zip zlib1g-dev git ccache

    - name: clone toolchain
      run: git clone --recursive https://source.codeaurora.org/quic/la/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9 -b LA.BR.1.3.6_rb1.14

    - name: clone kernel
      run: git clone --recursive https://github.com/Htylol/AndroModX-s2.git -b master

    - name: cd kernel
      run: cp -a aarch64-linux-android-4.9 AndroModX-s2
      run: cd AndroModX-s2

    - name: build
      run: ./build.sh
